spring:
  application:
    name: quick
  threads:
    virtual:
      enabled: true
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
  jooq:
    sql-dialect: MYSQL
  jackson:
    time-zone: UTC
    mapper:
      accept-case-insensitive-enums: true
  profiles:
    active: dev

server:
  port: 8080

springdoc:
  swagger-ui:
    path: /swagger-ui.html # 👉 OpenAPI JSON 문서 경로 (기본: /api-docs)
  api-docs:
    path: /api-docs  # 👉 Swagger UI 접속 경로 (기본: /swagger-ui/index.html)